select * from public.aliquote;
select * from public.analysis;
select * from public.analysis_entity;
select * from public.analyte;
select * from public.biospecimen;
select * from public.biospecimen_type;
select * from public."case";
select * from public.data_category;
select * from public.data_type;
select * from public.disease;
select * from public.experimental_strategy;
select * from public.gene;
select * from public.gene_expression_file;
select * from public.gene_type;
select * from public.portion;
select * from public.primary_site;
select * from public.project;
select * from public.protein;
select * from public.protein_expression_file;
select * from public.sample;
select * from public.sample_type;
select * from public.tumor;

delete from public.aliquote;
delete from public.analysis_entity;
delete from public.gene_expression_file;
delete from public.analysis;
delete from public.analyte;
delete from public.portion;
delete from public.sample;
delete from public.biospecimen;
delete from public."case";
delete from public.gene;
delete from public.project;
delete from public.protein;
delete from public.protein_expression_file;
delete from public.sample_type;
delete from public.tumor;
delete from public.disease;
